/** Static UI copy is bilingual; model-generated prose follows the request language. */
export type UiLanguage = "zh" | "en";

export function detectUiLanguage(text: string): UiLanguage {
  const cleaned = text.replace(/```[\s\S]*?```|`[^`]*`|https?:\/\/\S+/g, "");
  const prose = cleaned.replace(/"[^"\n]*"|“[^”\n]*”/g, "").trim() || text;
  if (/[\u3040-\u30ff\uac00-\ud7af]/.test(prose)) return "en";
  const chinese = (prose.match(/[\u3400-\u9fff]/g) || []).length;
  const words = (prose.match(/[A-Za-z]+/g) || []).length;
  return chinese > 0 && chinese >= words ? "zh" : "en";
}

const chineseCopy: Record<string, string> = {
  "Planning Research Dimensions": "规划调研维度",
  "Research dimensions created": "已生成调研维度",
  "Generating Search Queries": "生成搜索查询",
  "Web Research": "网页调研",
  "Reflection": "反思与复核",
  "Analysing Web Research Results": "正在分析网页调研结果",
  "Dimension Research Complete": "维度调研完成",
  "A research dimension was completed": "一个调研维度已完成",
  "Finalizing Answer": "整理最终报告",
  "Composing and presenting the final answer.": "正在整理并展示最终报告。",
  "Analyzing Research Topic": "分析调研主题",
  "The research topic is clear.": "调研主题已明确。",
  "Research Topic Clarified": "调研主题已澄清",
  "Accepted the proposed assumptions.": "已接受建议的假设。",
  "Research Dimensions Created": "调研维度已生成",
  "Research Dimensions Approved": "调研维度已通过",
  "Research Dimensions Rejected": "调研维度未通过",
  "Research can begin.": "可以开始调研。",
  "Dimension": "维度",
  "Initial evidence gaps planned.": "已规划初始证据缺口。",
  "Structured gap planning was unavailable; the full dimension scope was retained as a conservative gap.": "缺口规划暂不可用，已保守地将完整维度范围保留为待调研缺口。",
  "Evidence gap selected.": "已选择证据缺口。",
  "Structured query generation was unavailable; a deterministic gap-specific query was used.": "查询生成暂不可用，已使用针对当前缺口的兜底查询。",
  "Retrying Web Research": "重试网页搜索",
  "Web Research Failed": "网页搜索失败",
  "Web Research Complete": "网页搜索完成",
  "Structured source scoring was unavailable; conservative fallback scoring was applied.": "来源评分暂不可用，已采用保守的兜底评分。",
  "No direct evidence gain in this pass.": "本轮没有新增直接证据。",
  "Structured evidence matching was unavailable; the gap remained open conservatively.": "证据匹配暂不可用，为避免错误关闭，当前缺口仍保持未解决状态。",
  "Evidence gap": "证据缺口",
  "Escalating the search strategy.": "正在调整并加强搜索策略。",
  "Running a whole-dimension coverage audit.": "正在审计整个维度的覆盖情况。",
  "No actionable gap was added.": "没有新增可执行的证据缺口。",
  "Evidence is sufficient": "证据已充分",
  "Structured reflection was unavailable; conservative follow-up research was requested.": "反思结果暂不可用，已保守地安排补充调研。",
  "Planning Report Narrative": "规划报告结构",
  "the audited findings": "已审计的结论",
  "Report Planning Fallback": "报告规划降级",
  "A deterministic editorial plan preserved every audited claim.": "兜底报告规划已保留全部通过审计的结论。",
  "Drafting Research Report": "撰写调研报告",
  "Composing the report from audited dimension claims.": "正在基于各维度已审计的结论撰写报告。",
  "Report Audit Passed": "报告审计通过",
  "Report Revision Required": "报告需要修订",
  "Coverage, evidence, and citations passed review.": "覆盖范围、证据与引用已通过审查。",
  "Synthesizing all research dimensions.": "正在综合所有调研维度。",
  "Please provide the requested clarification.": "请补充需要澄清的信息。",
  "Please explain how the research dimensions should be revised.": "请说明需要如何调整调研维度。",
  "Error": "错误",
  "Retry": "重试",
  "Restoring previous research...": "正在恢复之前的调研…",
  "Clarify Research Topic": "澄清调研主题",
  "What needs clarification": "需要澄清的内容",
  "Questions": "问题",
  "Suggested assumptions": "建议的假设",
  "Your clarification": "补充说明",
  "Provide the missing scope, subject, or interpretation...": "请补充缺失的范围、对象或含义…",
  "Continue with Assumptions": "接受假设并继续",
  "Submit Clarification": "提交澄清信息",
  "Review Research Dimensions": "确认调研维度",
  "Revision feedback (required when rejecting)": "修改建议（不通过时必填）",
  "Describe missing perspectives, unwanted overlap, or a preferred focus...": "请说明缺失的视角、重复的内容或需要重点关注的方向…",
  "Regenerate with Feedback": "不通过，按建议重新生成",
  "Approve and Continue": "通过并继续",
  "Research": "调研进度",
  "Searching...": "正在调研…",
  "No activity to display.": "暂无调研活动。",
  "Timeline will update during processing.": "处理过程中将持续更新进度。",
  "Planning Evidence Gaps: {dimension}": "规划证据缺口：{dimension}",
  "Gap Planning Fallback: {dimension}": "缺口规划降级：{dimension}",
  "Researching Gap: {dimension}": "调研证据缺口：{dimension}",
  "Generating Queries: {dimension}": "生成查询：{dimension}",
  "Query Generation Fallback: {dimension}": "查询生成降级：{dimension}",
  "Evaluating Sources: {dimension}": "评估来源：{dimension}",
  "Source Evaluation Fallback: {dimension}": "来源评估降级：{dimension}",
  "Assessing Gap Evidence: {dimension}": "评估缺口证据：{dimension}",
  "Gap Evidence Fallback: {dimension}": "缺口证据评估降级：{dimension}",
  "Replanning Search: {dimension}": "重新规划搜索：{dimension}",
  "Evidence Gaps Processed: {dimension}": "证据缺口处理完成：{dimension}",
  "New Evidence Gaps: {dimension}": "新增证据缺口：{dimension}",
  "Reflection: {dimension}": "反思与复核：{dimension}",
  "Reflection Fallback: {dimension}": "反思降级：{dimension}",
  "Extracting Evidence Claims: {dimension}": "提取证据结论：{dimension}",
  "Gathered {count} sources. Related to: {labels}.": "已获取 {count} 个来源，相关内容：{labels}。",
  "{query} (attempt {attempt})": "{query}（第 {attempt} 次尝试）",
  "Gathered {count} sources for {query}": "针对 {query} 获取了 {count} 个来源",
  "{accepted} accepted, {supplementary} supplementary, {rejected} rejected from {candidates} candidates": "共 {candidates} 个候选来源：{accepted} 个通过，{supplementary} 个补充，{rejected} 个拒绝",
  "{count} new direct sources matched": "匹配到 {count} 个新的直接证据来源",
  "Gap Status: {status}": "缺口状态：{status}",
  "Strategy {level}: {strategy}": "策略级别 {level}：{strategy}",
  "{dimension} ({loops} gap searches, {status})": "{dimension}（{loops} 次缺口搜索，{status}）",
  "{count} auditable claims retained": "保留了 {count} 项可审计结论",
  "{count} sections organized around: {thesis}": "已规划 {count} 个章节，围绕：{thesis}",
  "Revising the report after audit {count}.": "正在根据第 {count} 次审计结果修订报告。",
  "open": "未开始",
  "active": "调研中",
  "partial": "部分解决",
  "closed": "已关闭",
  "stalled": "暂无进展",
  "unresolvable": "暂无法解决",
  "updated": "已更新",
  "sufficient": "证据充分",
  "complete": "完成",
  "researching": "调研中",
  "completed with limitations": "已完成，仍有局限",
  "web search unavailable": "网页搜索不可用",
  "gap_attempts_exhausted": "部分缺口达到搜索次数上限",
  "reflection_limit_reached": "达到维度复核上限",
  "no_progress": "连续复核没有新增有效证据",
  "source_quality_unmet": "来源质量要求未满足",
  "unresolved_contradiction": "仍有未解决的矛盾",
  "search_unavailable": "网页搜索不可用",
  "optional_or_duplicate_gaps_deferred": "重复或低影响缺口已延后",
  "final_gap_audit_unresolved": "最终审计仍有未关闭缺口",
  "unresolved_evidence": "仍有未解决的证据缺口"
};

const englishStatusCopy: Record<string, string> = {
  gap_attempts_exhausted: "search-attempt limit reached",
  reflection_limit_reached: "dimension-reflection limit reached",
  no_progress: "no new qualifying evidence",
  source_quality_unmet: "source quality requirements unmet",
  unresolved_contradiction: "unresolved contradictory evidence",
  search_unavailable: "web search unavailable",
  optional_or_duplicate_gaps_deferred: "duplicate or low-impact gaps deferred",
  final_gap_audit_unresolved: "final audit found unresolved gaps",
  unresolved_evidence: "unresolved evidence gaps",
};

export function translate(
  language: UiLanguage,
  key: string,
  values: Record<string, string | number> = {},
): string {
  const template = language === "zh" ? chineseCopy[key] ?? key : englishStatusCopy[key] ?? key;
  // Substitute once: source titles, queries and user content are never translated.
  return template.replace(/\{(\w+)\}/g, (match, name: string) => String(values[name] ?? match));
}
